"""Export a small, committable artifact bundle so the Streamlit app runs without
the full 156MB/2.7GB processed datasets (which stay gitignored and are
regenerated by scripts 01-03 from the raw download)."""
import sys
from pathlib import Path

import numpy as np
import scanpy as sc

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
MODEL_DIR = Path(__file__).resolve().parents[1] / "models"

print("Loading HVG matrix...")
hvg = sc.read_h5ad(DATA_DIR / "processed_hvg.h5ad")
control = hvg[hvg.obs["perturbation"].astype(str) == "control"]

rng = np.random.RandomState(0)
n_ref = min(1000, control.n_obs)
idx = rng.choice(control.n_obs, n_ref, replace=False)
control_ref = np.asarray(control.X[idx].todense()).astype(np.float32)

np.savez(
    MODEL_DIR / "app_artifacts.npz",
    hvg_genes=np.array(hvg.var_names),
    control_reference=control_ref,
)
print(f"Saved {n_ref} reference control cells x {control_ref.shape[1]} HVGs to models/app_artifacts.npz")
